name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r requirements.txt

    - uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: C:\Users\wgxnl\Desktop\AZERBAIJAN\dist

      

